language: python

python:
  - "2.7"

matrix:
  include:
    - python: "3.3"
      env:
        - DJANGO_VERSION=1.5
    - python: "3.3"
      env:
        - DJANGO_VERSION=1.6

env:
  - DJANGO_VERSION=1.3
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libjpeg62 libjpeg62-dev zlib1g-dev
  - sudo apt-get install -qq libgraphicsmagick++-dev libboost-python-dev
  - sudo apt-get install -qq imagemagick
  - sudo apt-get install -qq libmagickwand-dev

install:
  - pip install Redis
  - pip install Pillow
  - pip install Wand
  - pip install pgmagick
  - pip install django==$DJANGO_VERSION

script:
  - cd tests && sh runalltests.sh

branches:
  except:
    - legacy

notifications:
    irc:
        channels:
            - "irc.freenode.org#sorl-thumbnail"
        use_notice: true
        skip_join: true