language: python

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-django18-pil
    - python: "2.7"
      env: TOXENV=py27-django18-imagemagick
    - python: "2.7"
      env: TOXENV=py27-django18-graphicsmagick
    - python: "2.7"
      env: TOXENV=py27-django18-redis
    - python: "2.7"
      env: TOXENV=py27-django18-wand
    # - python: "2.7"
    #  env: TOXENV=py27-django18-pgmagick
    - python: "2.7"
      env: TOXENV=py27-django18-dbm

    - python: "3.4"
      env: TOXENV=py34-django18-pil
    - python: "3.4"
      env: TOXENV=py34-django18-imagemagick
    - python: "3.4"
      env: TOXENV=py34-django18-graphicsmagick
    - python: "3.4"
      env: TOXENV=py34-django18-redis
    - python: "3.4"
      env: TOXENV=py34-django18-wand
    - python: "3.4"
      env: TOXENV=py34-django18-dbm

    - python: "3.5"
      env: TOXENV=py35-django110-pil
    - python: "3.5"
      env: TOXENV=py35-django110-imagemagick
    - python: "3.5"
      env: TOXENV=py35-django110-graphicsmagick
    - python: "3.5"
      env: TOXENV=py35-django110-redis
    - python: "3.5"
      env: TOXENV=py35-django110-wand
    - python: "3.5"
      env: TOXENV=py35-django110-dbm

    - python: "3.6"
      env: TOXENV=py36-django111-pil
    - python: "3.6"
      env: TOXENV=py36-django111-imagemagick
    - python: "3.6"
      env: TOXENV=py36-django111-graphicsmagick
    - python: "3.6"
      env: TOXENV=py36-django111-redis
    - python: "3.6"
      env: TOXENV=py36-django111-wand
    - python: "3.6"
      env: TOXENV=py36-django111-dbm

sudo: false
dist: trusty

addons:
  apt:
    packages:
      - libgraphicsmagick1-dev
      # - libgraphicsmagick++1-dev
      # - libboost-python-dev
      - graphicsmagick
      - libjpeg62
      - zlib1g-dev

cache:
  apt: true
  directories:
    - .tox
    - $HOME/.cache/pip

after_failure:
  - cat /home/travis/.pip/pip.log

after_success: coveralls

install:
  - pip install -q flake8 tox coveralls

script:
  - env | sort
  - tox
  # - flake8 --show-source sorl/

services:
  - redis-server

notifications:
  email: false

deploy:
  provider: pypi
  user: jazzband
  distributions: sdist bdist_wheel
  password:
    secure: VD+63Tnv0VYNfFQv9f1KZ0k79HSX8veNk4dTy42Hriteci50z5uSQdZMnqqD83xQJa4VF6N7DHkxHnBVOWLCqGQZeYqR/5BuDFNUewcr6O14dk31HvxMsWDaN1KW0Qwtus8ZrztwGhZtZ/92ODA6luHI4mCTzqX0gcG0/aKd75s=
  on:
    tags: true
    repo: jazzband/sorl-thumbnail
