language: python

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-django18-pil APT='libjpeg62 libjpeg62-dev zlib1g-dev'
    - python: "2.7"
      env: TOXENV=py27-django18-imagemagick APT=imagemagick
    - python: "2.7"
      env: TOXENV=py27-django18-graphicsmagick APT=graphicsmagick
    - python: "2.7"
      env: TOXENV=py27-django18-redis
    - python: "2.7"
      env: TOXENV=py27-django18-wand
    - python: "2.7"
      env: TOXENV=py27-django18-pgmagick APT='libgraphicsmagick++1-dev libboost-python-dev'
    - python: "2.7"
      env: TOXENV=py27-django18-dbm

    - python: "3.4"
      env: TOXENV=py34-django18-pil APT='libjpeg62 libjpeg62-dev zlib1g-dev'
    - python: "3.4"
      env: TOXENV=py34-django18-imagemagick APT=imagemagick
    - python: "3.4"
      env: TOXENV=py34-django18-graphicsmagick APT=graphicsmagick
    - python: "3.4"
      env: TOXENV=py34-django18-redis
    - python: "3.4"
      env: TOXENV=py34-django18-wand
    - python: "3.4"
      env: TOXENV=py34-django18-dbm

    - python: "3.5"
      env: TOXENV=py35-django110-pil APT='libjpeg62 libjpeg62-dev zlib1g-dev'
    - python: "3.5"
      env: TOXENV=py35-django110-imagemagick APT=imagemagick
    - python: "3.5"
      env: TOXENV=py35-django110-graphicsmagick APT=graphicsmagick
    - python: "3.5"
      env: TOXENV=py35-django110-redis
    - python: "3.5"
      env: TOXENV=py35-django110-wand
    - python: "3.5"
      env: TOXENV=py35-django110-dbm

    - python: "3.6"
      env: TOXENV=py36-django111-pil APT='libjpeg62 libjpeg62-dev zlib1g-dev'
    - python: "3.6"
      env: TOXENV=py36-django111-imagemagick APT=imagemagick
    - python: "3.6"
      env: TOXENV=py36-django111-graphicsmagick APT=graphicsmagick
    - python: "3.6"
      env: TOXENV=py36-django111-redis
    - python: "3.6"
      env: TOXENV=py36-django111-wand
    - python: "3.6"
      env: TOXENV=py36-django111-dbm

cache:
  pip:
  apt:
  directories:
    - .tox

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq $APT

after_failure:
  - cat /home/travis/.pip/pip.log

after_success: coveralls

install:
  - pip install -q flake8 tox coveralls

script:
  - env | sort
  - tox
  - flake8 --show-source

services:
  - redis-server

notifications:
  email: false

deploy:
  provider: pypi
  user: jazzband
  distributions: sdist bdist_wheel
  password:
    secure: VD+63Tnv0VYNfFQv9f1KZ0k79HSX8veNk4dTy42Hriteci50z5uSQdZMnqqD83xQJa4VF6N7DHkxHnBVOWLCqGQZeYqR/5BuDFNUewcr6O14dk31HvxMsWDaN1KW0Qwtus8ZrztwGhZtZ/92ODA6luHI4mCTzqX0gcG0/aKd75s=
  on:
    tags: true
    repo: jazzband/sorl-thumbnail
